// The below code is generated by Claude 3.7

import { NextResponse } from "next/server";

// Public endpoint to get the default theme setting
export async function GET(request) {
  try {
    // Return the default theme (light)
    return NextResponse.json({ themePreference: 'light' });
  } catch (error) {
    console.error("Error in theme endpoint:", error);
    return NextResponse.json({ 
      error: "Failed to process request",
      details: error.message 
    }, { status: 500 });
  }
}